from .dashboard_chart_link import *
from .route_history import *
from .notification_log import *
from .form_tour import *
from .dashboard_chart_field import *
from .console_log import *
from .onboarding_permission import *
from .workspace_quick_list import *
from .notification_settings import *
from .workspace_shortcut import *
from .calendar_view import *
from .number_card_link import *
from .bulk_update import *
from .workspace_settings import *
from .note_seen_by import *
from .workspace_custom_block import *
from .system_console import *
from .tag_link import *
from .todo import *
from .dashboard_chart import *
from .dashboard_chart_source import *
from .system_health_report_errors import *
from .tag import *
from .list_filter import *
from .event_participants import *
from .list_view_settings import *
from .global_search_doctype import *
from .notification_subscribed_document import *
from .number_card import *
from .system_health_report_queue import *
from .dashboard import *
from .onboarding_step_map import *
from .system_health_report import *
from .kanban_board_column import *
from .global_search_settings import *
from .system_health_report_tables import *
from .kanban_board import *
from .desktop_icon import *
from .system_health_report_failing_jobs import *
from .workspace_number_card import *
from .event import *
from .form_tour_step import *
from .onboarding_step import *
from .module_onboarding import *
from .dashboard_settings import *
from .changelog_feed import *
from .workspace_chart import *
from .note import *
from .workspace import *
from .system_health_report_workers import *
from .workspace_link import *
from .custom_html_block import *
