# Generated by Django 4.2.5 on 2025-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0002_alter_aboutussettings_id_alter_audittrail_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_error_traceback",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_guests_to_upload_files",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_login_using_mobile_number",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_login_using_user_name",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_older_web_view_links",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="apply_strict_user_permissions",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="attach_view_link",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="bypass_2fa_for_retricted_ip_users",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="bypass_restrict_ip_check_if_2fa_enabled",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="deny_multiple_sessions",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_change_log_notification",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_document_sharing",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_standard_email_footer",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_system_update_notification",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_user_pass_login",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_onboarding",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_password_policy",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_scheduler",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_telemetry",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_two_factor_auth",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="encrypt_backup",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="force_web_capture_mode_for_uploads",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="hide_empty_read_only_fields",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="hide_footer_in_auto_email_reports",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="login_with_email_link",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="logout_on_password_reset",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setup_complete",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="store_attached_pdf_document",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="strip_exif_metadata_from_uploaded_images",
            field=models.CharField(blank=True, default="1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="use_number_format_from_currency",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
    ]
