# Generated by Django 4.2.5 on 2025-03-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0003_alter_systemsettings_allow_error_traceback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="reset_password_link_expiry_duration",
            field=models.DurationField(blank=True, default=1200, null=True),
        ),
    ]
