# Generated by Django 4.2.5 on 2025-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0007_alter_address_disabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_consecutive_login_attempts",
            field=models.IntegerField(blank=True, default="10", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_error_traceback",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_guests_to_upload_files",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_login_after_fail",
            field=models.IntegerField(blank=True, default="60", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_login_using_mobile_number",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_login_using_user_name",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_older_web_view_links",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="apply_strict_user_permissions",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="attach_view_link",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="backup_limit",
            field=models.IntegerField(blank=True, default="3", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="bypass_2fa_for_retricted_ip_users",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="bypass_restrict_ip_check_if_2fa_enabled",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="deny_multiple_sessions",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_change_log_notification",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_document_sharing",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_standard_email_footer",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_system_update_notification",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="disable_user_pass_login",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="document_share_key_expiry",
            field=models.IntegerField(blank=True, default="30", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="dormant_days",
            field=models.IntegerField(blank=True, default="4", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="email_retry_limit",
            field=models.IntegerField(blank=True, default="3", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_onboarding",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_password_policy",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_scheduler",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_telemetry",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_two_factor_auth",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="encrypt_backup",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="force_web_capture_mode_for_uploads",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="hide_empty_read_only_fields",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="hide_footer_in_auto_email_reports",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="link_field_results_limit",
            field=models.IntegerField(blank=True, default="10", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="login_with_email_link",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="login_with_email_link_expiry",
            field=models.IntegerField(blank=True, default="10", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="logout_on_password_reset",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_auto_email_report_per_user",
            field=models.IntegerField(blank=True, default="20", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="password_reset_limit",
            field=models.IntegerField(blank=True, default="3", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="reset_password_link_expiry_duration",
            field=models.DurationField(blank=True, default="1200", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setup_complete",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="store_attached_pdf_document",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="strip_exif_metadata_from_uploaded_images",
            field=models.BooleanField(blank=True, default="1", null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="use_number_format_from_currency",
            field=models.BooleanField(blank=True, default="0", null=True),
        ),
    ]
