# Generated by Django 4.2.5 on 2025-03-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0009_alter_address_disabled_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="new_password",
            new_name="password",
        ),
    ]
