# Generated by Django 4.2.5 on 2025-03-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0011_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="new_password",
        ),
    ]
