# Generated by Django 4.2.5 on 2025-03-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("frappe_app", "0012_rename_password_user_new_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                blank=True,
                default="System User",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserUserType",
                to="frappe_app.usertype",
            ),
        ),
    ]
