from django.db import models
from multiselectfield import MultiSelectField
from core.models.template import BaseModel, SingletonModel
import uuid
import os
from django.conf import settings

class WebForm(BaseModel):
    title = models.CharField(max_length=255, null=True, blank=True)
    route = models.CharField(max_length=255, null=True, blank=True)
    doc_type = models.ForeignKey("frappe_app.Doctype", related_name="WebFormDocType", on_delete=models.CASCADE, null=True, blank=True)
    module = models.ForeignKey("frappe_app.ModuleDef", related_name="WebFormModule", on_delete=models.CASCADE, null=True, blank=True)
    is_standard = models.BooleanField(default=False, null=True, blank=True)
    published = models.BooleanField(default=False, null=True, blank=True)
    login_required = models.BooleanField(default=False, null=True, blank=True)
    allow_edit = models.BooleanField(default=False, null=True, blank=True)
    allow_multiple = models.BooleanField(default=False, null=True, blank=True)
    allow_delete = models.BooleanField(default=False, null=True, blank=True)
    allow_print = models.BooleanField(default=False, null=True, blank=True)
    print_format = models.ForeignKey("frappe_app.PrintFormat", related_name="WebFormPrintFormat", on_delete=models.CASCADE, null=True, blank=True)
    allow_comments = models.BooleanField(default=False, null=True, blank=True)
    show_attachments = models.BooleanField(default=False, null=True, blank=True)
    allow_incomplete = models.BooleanField(default=False, null=True, blank=True)
    introduction_text = models.CharField(max_length=255, null=True, blank=True)
    web_form_fields = models.ManyToManyField("frappe_app.WebFormField", related_name="WebFormWebFormFields", )
    max_attachment_size = models.IntegerField(null=True, blank=True)
    client_script = models.CharField(max_length=255, null=True, blank=True)
    button_label = models.CharField(max_length=255, default='Save', null=True, blank=True)
    success_message = models.TextField(null=True, blank=True)
    success_url = models.CharField(max_length=255, null=True, blank=True)
    show_sidebar = models.BooleanField(default=False, null=True, blank=True)
    breadcrumbs = models.CharField(max_length=255, null=True, blank=True)
    custom_css = models.CharField(max_length=255, null=True, blank=True)
    apply_document_permissions = models.BooleanField(default=False, null=True, blank=True)
    show_list = models.BooleanField(default=False, null=True, blank=True)
    list_title = models.CharField(max_length=255, null=True, blank=True)
    list_columns = models.ManyToManyField("frappe_app.WebFormListColumn", related_name="WebFormListColumns", )
    website_sidebar = models.ForeignKey("frappe_app.WebsiteSidebar", related_name="WebFormWebsiteSidebar", on_delete=models.CASCADE, null=True, blank=True)
    list_setting_message = models.TextField(null=True, blank=True)
    success_title = models.CharField(max_length=255, null=True, blank=True)
    banner_image = models.CharField(max_length=255, null=True, blank=True)
    meta_title = models.CharField(max_length=255, null=True, blank=True)
    meta_description = models.TextField(null=True, blank=True)
    meta_image = models.CharField(max_length=255, null=True, blank=True)
    anonymous = models.BooleanField(default=False, null=True, blank=True)
    condition_description = models.TextField(null=True, blank=True)
    condition_json = models.JSONField(null=True, blank=True)
    hide_navbar = models.BooleanField(default=False, null=True, blank=True)
    hide_footer = models.BooleanField(default=False, null=True, blank=True)
    allowed_embedding_domains = models.TextField(null=True, blank=True)
