from django.db import models
from multiselectfield import MultiSelectField
from core.models.template import BaseModel, SingletonModel
import uuid
import os
from django.conf import settings

class WebsiteSettings(SingletonModel):
    home_page = models.CharField(max_length=255, null=True, blank=True)
    title_prefix = models.CharField(max_length=255, null=True, blank=True)
    website_theme = models.ForeignKey("frappe_app.WebsiteTheme", related_name="WebsiteSettingsWebsiteTheme", on_delete=models.CASCADE, default='Standard', null=True, blank=True)
    website_theme_image = models.CharField(max_length=255, null=True, blank=True)
    website_theme_image_link = models.CharField(max_length=255, null=True, blank=True)
    banner_image = models.CharField(max_length=255, null=True, blank=True)
    brand_html = models.CharField(max_length=255, null=True, blank=True)
    set_banner_from_image = models.CharField(max_length=255, null=True, blank=True)
    navbar_search = models.BooleanField(default=False, null=True, blank=True)
    top_bar_items = models.ManyToManyField("frappe_app.TopBarItem", related_name="WebsiteSettingsTopBarItems", )
    banner_html = models.CharField(max_length=255, null=True, blank=True)
    copyright = models.CharField(max_length=255, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    footer_items = models.ManyToManyField("frappe_app.TopBarItem", related_name="WebsiteSettingsFooterItems", )
    hide_footer_signup = models.BooleanField(default=False, null=True, blank=True)
    google_analytics_id = models.CharField(max_length=255, null=True, blank=True)
    favicon = models.CharField(max_length=255, null=True, blank=True)
    subdomain = models.TextField(null=True, blank=True)
    disable_signup = models.BooleanField(default=True, null=True, blank=True)
    head_html = models.CharField(max_length=255, null=True, blank=True)
    robots_txt = models.CharField(max_length=255, null=True, blank=True)
    route_redirects = models.ManyToManyField("frappe_app.WebsiteRouteRedirect", related_name="WebsiteSettingsRouteRedirects", )
    enable_google_indexing = models.BooleanField(default=False, null=True, blank=True)
    indexing_refresh_token = models.CharField(max_length=255, null=True, blank=True)
    indexing_authorization_code = models.CharField(max_length=255, null=True, blank=True)
    authorize_api_indexing_access = models.CharField(max_length=255, null=True, blank=True)
    enable_view_tracking = models.BooleanField(default=False, null=True, blank=True)
    footer_logo = models.CharField(max_length=255, null=True, blank=True)
    call_to_action = models.CharField(max_length=255, null=True, blank=True)
    call_to_action_url = models.CharField(max_length=255, null=True, blank=True)
    hide_login = models.BooleanField(default=False, null=True, blank=True)
    navbar_template = models.ForeignKey("frappe_app.WebTemplate", related_name="WebsiteSettingsNavbarTemplate", on_delete=models.CASCADE, null=True, blank=True)
    navbar_template_values = models.CharField(max_length=255, null=True, blank=True)
    edit_navbar_template_values = models.CharField(max_length=255, null=True, blank=True)
    footer_template = models.ForeignKey("frappe_app.WebTemplate", related_name="WebsiteSettingsFooterTemplate", on_delete=models.CASCADE, null=True, blank=True)
    footer_template_values = models.CharField(max_length=255, null=True, blank=True)
    edit_footer_template_values = models.CharField(max_length=255, null=True, blank=True)
    google_analytics_anonymize_ip = models.BooleanField(default=True, null=True, blank=True)
    show_language_picker = models.BooleanField(default=False, null=True, blank=True)
    app_name = models.CharField(max_length=255, default='Frappe', null=True, blank=True)
    app_logo = models.CharField(max_length=255, null=True, blank=True)
    show_account_deletion_link = models.BooleanField(default=False, null=True, blank=True)
    auto_account_deletion = models.IntegerField(default=72, null=True, blank=True)
    footer_powered = models.TextField(null=True, blank=True)
    splash_image = models.CharField(max_length=255, null=True, blank=True)
    show_footer_on_login = models.BooleanField(default=False, null=True, blank=True)
